# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from metapod.v1 import metapod_pb2 as metapod_dot_v1_dot_metapod__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in metapod/v1/metapod_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MetapodServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Create = channel.unary_unary(
                '/metapod.v1.MetapodService/Create',
                request_serializer=metapod_dot_v1_dot_metapod__pb2.CreateRequest.SerializeToString,
                response_deserializer=metapod_dot_v1_dot_metapod__pb2.CreateResponse.FromString,
                _registered_method=True)
        self.Analyze = channel.unary_unary(
                '/metapod.v1.MetapodService/Analyze',
                request_serializer=metapod_dot_v1_dot_metapod__pb2.AnalyzeRequest.SerializeToString,
                response_deserializer=metapod_dot_v1_dot_metapod__pb2.AnalyzeResponse.FromString,
                _registered_method=True)
        self.Status = channel.unary_unary(
                '/metapod.v1.MetapodService/Status',
                request_serializer=metapod_dot_v1_dot_metapod__pb2.StatusRequest.SerializeToString,
                response_deserializer=metapod_dot_v1_dot_metapod__pb2.StatusResponse.FromString,
                _registered_method=True)


class MetapodServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Analyze(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Status(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MetapodServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=metapod_dot_v1_dot_metapod__pb2.CreateRequest.FromString,
                    response_serializer=metapod_dot_v1_dot_metapod__pb2.CreateResponse.SerializeToString,
            ),
            'Analyze': grpc.unary_unary_rpc_method_handler(
                    servicer.Analyze,
                    request_deserializer=metapod_dot_v1_dot_metapod__pb2.AnalyzeRequest.FromString,
                    response_serializer=metapod_dot_v1_dot_metapod__pb2.AnalyzeResponse.SerializeToString,
            ),
            'Status': grpc.unary_unary_rpc_method_handler(
                    servicer.Status,
                    request_deserializer=metapod_dot_v1_dot_metapod__pb2.StatusRequest.FromString,
                    response_serializer=metapod_dot_v1_dot_metapod__pb2.StatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'metapod.v1.MetapodService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('metapod.v1.MetapodService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MetapodService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/metapod.v1.MetapodService/Create',
            metapod_dot_v1_dot_metapod__pb2.CreateRequest.SerializeToString,
            metapod_dot_v1_dot_metapod__pb2.CreateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Analyze(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/metapod.v1.MetapodService/Analyze',
            metapod_dot_v1_dot_metapod__pb2.AnalyzeRequest.SerializeToString,
            metapod_dot_v1_dot_metapod__pb2.AnalyzeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Status(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/metapod.v1.MetapodService/Status',
            metapod_dot_v1_dot_metapod__pb2.StatusRequest.SerializeToString,
            metapod_dot_v1_dot_metapod__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
