# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: metapod/v1/metapod.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'metapod/v1/metapod.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18metapod/v1/metapod.proto\x12\nmetapod.v1\"K\n\rCreateRequest\x12\r\n\x05\x62rand\x18\x01 \x01(\t\x12\x0f\n\x07\x63hannel\x18\x02 \x01(\t\x12\n\n\x02id\x18\x03 \x01(\t\x12\x0e\n\x06prompt\x18\x04 \x01(\t\",\n\x0e\x43reateResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\t2Q\n\x0eMetapodService\x12?\n\x06\x43reate\x12\x19.metapod.v1.CreateRequest\x1a\x1a.metapod.v1.CreateResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'metapod.v1.metapod_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATEREQUEST']._serialized_start=40
  _globals['_CREATEREQUEST']._serialized_end=115
  _globals['_CREATERESPONSE']._serialized_start=117
  _globals['_CREATERESPONSE']._serialized_end=161
  _globals['_METAPODSERVICE']._serialized_start=163
  _globals['_METAPODSERVICE']._serialized_end=244
# @@protoc_insertion_point(module_scope)
