# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: profanity/v1/profanity.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'profanity/v1/profanity.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cprofanity/v1/profanity.proto\x12\x0cprofanity.v1\"\"\n\x12\x41nalyzeTextRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"\x83\x01\n\x13\x41nalyzeTextResponse\x12=\n\x06probas\x18\x01 \x03(\x0b\x32-.profanity.v1.AnalyzeTextResponse.ProbasEntry\x1a-\n\x0bProbasEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01:\x02\x38\x01\"\"\n\x13\x41nalyzeImageRequest\x12\x0b\n\x03url\x18\x01 \x01(\t\"/\n\x14\x41nalyzeImageResponse\x12\x17\n\x0fprofanity_check\x18\x01 \x01(\x08\x32\xbd\x01\n\x10ProfanityService\x12R\n\x0b\x41nalyzeText\x12 .profanity.v1.AnalyzeTextRequest\x1a!.profanity.v1.AnalyzeTextResponse\x12U\n\x0c\x41nalyzeImage\x12!.profanity.v1.AnalyzeImageRequest\x1a\".profanity.v1.AnalyzeImageResponseB8Z6benimaru/gateway/internal/gen/profanity/v1;profanityv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'profanity.v1.profanity_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z6benimaru/gateway/internal/gen/profanity/v1;profanityv1'
  _globals['_ANALYZETEXTRESPONSE_PROBASENTRY']._loaded_options = None
  _globals['_ANALYZETEXTRESPONSE_PROBASENTRY']._serialized_options = b'8\001'
  _globals['_ANALYZETEXTREQUEST']._serialized_start=46
  _globals['_ANALYZETEXTREQUEST']._serialized_end=80
  _globals['_ANALYZETEXTRESPONSE']._serialized_start=83
  _globals['_ANALYZETEXTRESPONSE']._serialized_end=214
  _globals['_ANALYZETEXTRESPONSE_PROBASENTRY']._serialized_start=169
  _globals['_ANALYZETEXTRESPONSE_PROBASENTRY']._serialized_end=214
  _globals['_ANALYZEIMAGEREQUEST']._serialized_start=216
  _globals['_ANALYZEIMAGEREQUEST']._serialized_end=250
  _globals['_ANALYZEIMAGERESPONSE']._serialized_start=252
  _globals['_ANALYZEIMAGERESPONSE']._serialized_end=299
  _globals['_PROFANITYSERVICE']._serialized_start=302
  _globals['_PROFANITYSERVICE']._serialized_end=491
# @@protoc_insertion_point(module_scope)
