# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from profanity.v1 import profanity_pb2 as profanity_dot_v1_dot_profanity__pb2


class ProfanityServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AnalyzeText = channel.unary_unary(
                '/profanity.v1.ProfanityService/AnalyzeText',
                request_serializer=profanity_dot_v1_dot_profanity__pb2.AnalyzeTextRequest.SerializeToString,
                response_deserializer=profanity_dot_v1_dot_profanity__pb2.AnalyzeTextResponse.FromString,
                _registered_method=True)
        self.AnalyzeImage = channel.unary_unary(
                '/profanity.v1.ProfanityService/AnalyzeImage',
                request_serializer=profanity_dot_v1_dot_profanity__pb2.AnalyzeImageRequest.SerializeToString,
                response_deserializer=profanity_dot_v1_dot_profanity__pb2.AnalyzeImageResponse.FromString,
                _registered_method=True)


class ProfanityServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def AnalyzeText(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnalyzeImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProfanityServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AnalyzeText': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeText,
                    request_deserializer=profanity_dot_v1_dot_profanity__pb2.AnalyzeTextRequest.FromString,
                    response_serializer=profanity_dot_v1_dot_profanity__pb2.AnalyzeTextResponse.SerializeToString,
            ),
            'AnalyzeImage': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeImage,
                    request_deserializer=profanity_dot_v1_dot_profanity__pb2.AnalyzeImageRequest.FromString,
                    response_serializer=profanity_dot_v1_dot_profanity__pb2.AnalyzeImageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'profanity.v1.ProfanityService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('profanity.v1.ProfanityService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ProfanityService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AnalyzeText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/profanity.v1.ProfanityService/AnalyzeText',
            profanity_dot_v1_dot_profanity__pb2.AnalyzeTextRequest.SerializeToString,
            profanity_dot_v1_dot_profanity__pb2.AnalyzeTextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AnalyzeImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/profanity.v1.ProfanityService/AnalyzeImage',
            profanity_dot_v1_dot_profanity__pb2.AnalyzeImageRequest.SerializeToString,
            profanity_dot_v1_dot_profanity__pb2.AnalyzeImageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
