# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: profanity/v1/profanity.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'profanity/v1/profanity.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cprofanity/v1/profanity.proto\x12\x0cprofanity.v1\"(\n\x12\x41nalyzeTextRequest\x12\x12\n\x04text\x18\x01 \x01(\tR\x04text\"\x97\x01\n\x13\x41nalyzeTextResponse\x12\x45\n\x06probas\x18\x01 \x03(\x0b\x32-.profanity.v1.AnalyzeTextResponse.ProbasEntryR\x06probas\x1a\x39\n\x0bProbasEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n\x05value\x18\x02 \x01(\x01R\x05value:\x02\x38\x01\"\'\n\x13\x41nalyzeImageRequest\x12\x10\n\x03url\x18\x01 \x01(\tR\x03url\"?\n\x14\x41nalyzeImageResponse\x12\'\n\x0fprofanity_check\x18\x01 \x01(\x08R\x0eprofanityCheck2\xbd\x01\n\x10ProfanityService\x12R\n\x0b\x41nalyzeText\x12 .profanity.v1.AnalyzeTextRequest\x1a!.profanity.v1.AnalyzeTextResponse\x12U\n\x0c\x41nalyzeImage\x12!.profanity.v1.AnalyzeImageRequest\x1a\".profanity.v1.AnalyzeImageResponseB8Z6benimaru/gateway/internal/gen/profanity/v1;profanityv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'profanity.v1.profanity_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z6benimaru/gateway/internal/gen/profanity/v1;profanityv1'
  _globals['_ANALYZETEXTRESPONSE_PROBASENTRY']._loaded_options = None
  _globals['_ANALYZETEXTRESPONSE_PROBASENTRY']._serialized_options = b'8\001'
  _globals['_ANALYZETEXTREQUEST']._serialized_start=46
  _globals['_ANALYZETEXTREQUEST']._serialized_end=86
  _globals['_ANALYZETEXTRESPONSE']._serialized_start=89
  _globals['_ANALYZETEXTRESPONSE']._serialized_end=240
  _globals['_ANALYZETEXTRESPONSE_PROBASENTRY']._serialized_start=183
  _globals['_ANALYZETEXTRESPONSE_PROBASENTRY']._serialized_end=240
  _globals['_ANALYZEIMAGEREQUEST']._serialized_start=242
  _globals['_ANALYZEIMAGEREQUEST']._serialized_end=281
  _globals['_ANALYZEIMAGERESPONSE']._serialized_start=283
  _globals['_ANALYZEIMAGERESPONSE']._serialized_end=346
  _globals['_PROFANITYSERVICE']._serialized_start=349
  _globals['_PROFANITYSERVICE']._serialized_end=538
# @@protoc_insertion_point(module_scope)
