# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: profanity/v1/profanity.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'profanity/v1/profanity.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cprofanity/v1/profanity.proto\x12\x0cprofanity.v1\"\x1e\n\x0e\x41nalyzeRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"{\n\x0f\x41nalyzeResponse\x12\x39\n\x06probas\x18\x01 \x03(\x0b\x32).profanity.v1.AnalyzeResponse.ProbasEntry\x1a-\n\x0bProbasEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01:\x02\x38\x01\x32Z\n\x10ProfanityService\x12\x46\n\x07\x41nalyze\x12\x1c.profanity.v1.AnalyzeRequest\x1a\x1d.profanity.v1.AnalyzeResponseB8Z6benimaru/gateway/internal/gen/profanity/v1;profanityv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'profanity.v1.profanity_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z6benimaru/gateway/internal/gen/profanity/v1;profanityv1'
  _globals['_ANALYZERESPONSE_PROBASENTRY']._loaded_options = None
  _globals['_ANALYZERESPONSE_PROBASENTRY']._serialized_options = b'8\001'
  _globals['_ANALYZEREQUEST']._serialized_start=46
  _globals['_ANALYZEREQUEST']._serialized_end=76
  _globals['_ANALYZERESPONSE']._serialized_start=78
  _globals['_ANALYZERESPONSE']._serialized_end=201
  _globals['_ANALYZERESPONSE_PROBASENTRY']._serialized_start=156
  _globals['_ANALYZERESPONSE_PROBASENTRY']._serialized_end=201
  _globals['_PROFANITYSERVICE']._serialized_start=203
  _globals['_PROFANITYSERVICE']._serialized_end=293
# @@protoc_insertion_point(module_scope)
